name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn package
      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_SIG }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASS }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          # Trust the key (optional but recommended)
          KEY_ID=$(gpg --list-keys --with-colons | grep '^pub' | cut -d':' -f5)
          echo -e "5\ny\n" | gpg --command-fd 0 --edit-key $KEY_ID trust

          # Configure git to use this key for signing
          git config --global user.signingkey $KEY_ID
          git config --global commit.gpgsign true

          # Setup gpg-agent with passphrase for signing
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg.conf

      - name: Setup GPG agent for password
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo RELOADAGENT | gpg-connect-agent
          echo "passphrase=$GPG_PASSPHRASE" | gpg --batch --pinentry-mode loopback --passphrase-fd 0 --sign --dry-run somefile || true
      - name: Commit and push jar
        run: |
          git config user.name "Wdboyes13"
          git config user.email "willdev2025@outlook.com"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Auto-build jar"
            git push origin main
          else
            echo "No changes to commit. :3"
          fi